version: '3'

services:
  db:
    container_name: server-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=t_usr
      - MYSQL_PASSWORD=jruizdev 
      - MYSQL_DATABASE=debug_db
    restart: always
    ports:
      - '3307:3306'
